// flow-typed signature: 0f2762e4d71bf868820d1b5dc90bd690
// flow-typed version: <<STUB>>/remove-webpack-plugin_v^1.1.0/flow_v0.32.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'remove-webpack-plugin'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'remove-webpack-plugin' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'remove-webpack-plugin/index' {
  declare module.exports: $Exports<'remove-webpack-plugin'>;
}
declare module 'remove-webpack-plugin/index.js' {
  declare module.exports: $Exports<'remove-webpack-plugin'>;
}
